### ISSUE TITLE
Compatibility with Node 6.9.2?

### ISSUE THREAD

**Issue by siamkreative** [itsKaynine/thailand-post-api#2]
Hi there,

I just updated to Node 6.9.2 and it looks like it's not working anymore.

```javascript
trackService.init(function (err, serv) {
	var barcode = "EN331755897TH";

	serv.getItem(barcode, function (err, result) {
		if (err) {
			return console.log(err);
		}

		console.log(result);
	});
});
```

It generates **ReferenceError: serv is not defined**

**Comment by itsKaynine** [comment]
@SiamKreative Hi, sorry for the slow response. This **might** caused from the outdated [soap](https://www.npmjs.com/package/soap) package. I'll get back to you when I have a chance to try it out on latest version of Node. For now you can try updating the soap package.

**Comment by siamkreative** [comment]
No worries, take your time. I actually think that the issue comes from my setup... Locally, my small app runs fine with `Node.js 7.0.0` and `npm 3.10.8` but it leads to a 503 on my DigitalOcean droplet.

Because I have limited DevOps experience, I have been trying to figure this out for a week...

**Comment by siamkreative** [comment]
If I remove `trackService`, the server runs without a problem instead of timing out.

**Comment by itsKaynine** [comment]
Hi, I just tested locally and everything seems to work fine. My bet is that they (thailandpost server) have blacklisted all connections from VPS providers like DigitalOcean, which makes the client unable to reach through SOAP. Again that is just a guess, I will investigate further and try it with VPN or something. Sorry for the late reply.

**Comment by itsKaynine** [comment]
**UPDATE**

@SiamKreative  The problem seems to be related to the machine's timezone which caused the keygen to generate the wrong PublicXmlKey. I released version 2.1.0 to fix this bug.

Now I've successfully run demo.js in DigitalOcean SGP1 on Node v7.4.0.

**Comment by siamkreative** [comment]
Thanks I will try asap :)

**Comment by siamkreative** [comment]
How can I contact you? I am unable still unable to run my app on DigitalOcean (using the [default node.js image](https://www.digitalocean.com/products/one-click-apps/node-js/)). Maybe there is some firewall issues that I am not aware of?
